pin nokogiri version
Pinning nokogiri version prevents errors when installing the Gem in
custom environments. e.g.

ERROR:  Error installing sensu-plugins-aws:
	The last version of nokogiri (>= 1.10.4, < 2.0) to support your
	Ruby & RubyGems was 1.10.10. Try installing it with `gem install nokogiri -v 1.10.10`
	and then running the current command again
	nokogiri requires Ruby version >= 2.5, < 3.1.dev. The current ruby version is 2.4.10.364.